# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('owner_role', models.CharField(choices=[('USER', 'User'), ('RIDER', 'Rider')], max_length=10)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('qr_code_url', models.CharField(blank=True, max_length=500, null=True)),
                ('total_used', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'referral_codes',
            },
        ),
        migrations.CreateModel(
            name='ReferralMonthlyTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField()),
                ('owner_role', models.CharField(choices=[('USER', 'User'), ('RIDER', 'Rider')], max_length=10)),
                ('month_year', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('points_credited', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'referral_monthly_trackers',
                'unique_together': {('owner_id', 'owner_role', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('referred_id', models.UUIDField()),
                ('referred_role', models.CharField(choices=[('USER', 'User'), ('RIDER', 'Rider')], max_length=10)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('REGISTERED', 'Registered'), ('QUALIFIED', 'Qualified'), ('CREDITED', 'Credited'), ('CAP_REACHED', 'Cap Reached')], default='INVITED', max_length=15)),
                ('points_credited', models.IntegerField(default=0)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='referrals.referralcode')),
            ],
            options={
                'db_table': 'referral_records',
            },
        ),
    ]
