# Generated by Django 5.1.2 on 2026-03-07 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('recipient_role', models.CharField(choices=[('USER', 'User'), ('MERCHANT', 'Merchant'), ('RIDER', 'Rider'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], max_length=15)),
                ('channel', models.CharField(choices=[('PUSH_FCM', 'FCM Push'), ('WEB_PUSH', 'Web Push'), ('IN_APP', 'In-App'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='PUSH_FCM', max_length=15)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data_payload', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=15)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('owner_role', models.CharField(choices=[('USER', 'User'), ('MERCHANT', 'Merchant'), ('RIDER', 'Rider'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], max_length=15)),
                ('device_id', models.CharField(max_length=255)),
                ('fcm_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fcm_tokens',
                'unique_together': {('owner_id', 'device_id')},
            },
        ),
    ]
