# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('participant_id', models.UUIDField(db_index=True)),
                ('participant_role', models.CharField(choices=[('RIDER', 'Rider'), ('USER', 'User'), ('MERCHANT', 'Merchant')], max_length=15)),
                ('is_archived', models.BooleanField(default=False)),
                ('unread_count_admin', models.IntegerField(default=0)),
                ('unread_count_participant', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='accounts.adminprofile')),
            ],
            options={
                'db_table': 'chat_threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender_id', models.UUIDField()),
                ('sender_role', models.CharField(choices=[('ADMIN', 'Admin'), ('RIDER', 'Rider'), ('USER', 'User'), ('MERCHANT', 'Merchant')], max_length=15)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('SYSTEM', 'System')], default='TEXT', max_length=10)),
                ('body', models.TextField(blank=True, null=True)),
                ('attachment_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='GCash screenshot verified')),
                ('wallet_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chatthread')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
