# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('store_type', models.CharField(choices=[('SHOP', 'Shop'), ('FRESH_MARKET', 'Fresh Market'), ('READY_TO_EAT', 'Ready to Eat'), ('PRELOVED', 'Pre-Loved')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_MERCHANT', 'Pending Merchant'), ('MERCHANT_ACCEPTED', 'Merchant Accepted'), ('PREPARING', 'Preparing'), ('COOKING', 'Cooking'), ('FOR_PICKUP', 'For Pickup'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('TIMEOUT_CANCELLED', 'Timeout Cancelled'), ('FAILED', 'Failed')], default='PENDING_MERCHANT', max_length=20)),
                ('delivery_method', models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup')], default='DELIVERY', max_length=10)),
                ('vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_speed', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('SAVER', 'Saver')], max_length=10, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('markup_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rapex_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('merchant_accept_deadline', models.DateTimeField(blank=True, null=True)),
                ('pickup_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.merchantprofile')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.riderprofile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='merchant.merchantstore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_id', models.UUIDField()),
                ('product_type', models.CharField(choices=[('SHOP', 'Shop'), ('FRESH', 'Fresh Market'), ('FOOD', 'Ready to Eat'), ('PRELOVED', 'Pre-Loved')], max_length=20)),
                ('product_name', models.CharField(max_length=300)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('add_ons', models.JSONField(blank=True, null=True)),
                ('special_note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_by_role', models.CharField(choices=[('SYSTEM', 'System'), ('MERCHANT', 'Merchant'), ('RIDER', 'Rider'), ('ADMIN', 'Admin'), ('USER', 'User')], max_length=20)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': 'order_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
