# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFareConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('4_WHEELS', '4 Wheels')], max_length=20, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard_addon', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('saver_addon', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('surcharge_per_km', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('base_coverage_km', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'delivery_fare_config',
            },
        ),
        migrations.CreateModel(
            name='RiderDeliverySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('gps_track', models.JSONField(blank=True, default=list, help_text='[{lat, lng, ts}, ...]')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_session', to='orders.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sessions', to='accounts.riderprofile')),
            ],
            options={
                'db_table': 'rider_delivery_sessions',
            },
        ),
    ]
