# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MERCHANT', 'Merchant'), ('RIDER', 'Rider'), ('USER', 'User')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('sub_role', models.CharField(choices=[('OPERATIONS', 'Operations Manager'), ('SUPPORT', 'Support Agent'), ('FINANCE', 'Finance Officer'), ('COMPLIANCE', 'Compliance Officer'), ('LOGISTICS', 'Logistics Manager')], default='OPERATIONS', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
            },
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, default='')),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('business_address', models.TextField(blank=True, default='')),
                ('business_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('business_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('kyc_rejection_reason', models.TextField(blank=True, null=True)),
                ('kyc_id_photo', models.CharField(blank=True, default='', max_length=500)),
                ('kyc_selfie_photo', models.CharField(blank=True, default='', max_length=500)),
                ('kyc_business_doc', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchantprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Profile',
            },
        ),
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN', 'Login'), ('RESET', 'Password Reset')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used'], name='accounts_ot_phone_04dbc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, default='')),
                ('home_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('home_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('4_WHEELS', '4-Wheels')], default='MOTORCYCLE', max_length=20)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('kyc_rejection_reason', models.TextField(blank=True, null=True)),
                ('kyc_id_photo', models.CharField(blank=True, default='', max_length=500)),
                ('kyc_selfie_photo', models.CharField(blank=True, default='', max_length=500)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('background_check_flagged', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riderprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Profile',
            },
        ),
        migrations.CreateModel(
            name='SuperAdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadminprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SuperAdmin Profile',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, default='')),
                ('home_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('home_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('kyc_id_type', models.CharField(blank=True, default='', max_length=50)),
                ('kyc_id_photo', models.CharField(blank=True, default='', max_length=500)),
                ('kyc_selfie_photo', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='accounts_cu_role_0d7945_idx'),
        ),
    ]
