# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed'), ('ADJUSTED', 'Adjusted'), ('EXPIRED', 'Expired')], max_length=20)),
                ('points', models.IntegerField()),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RapexWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.UUIDField()),
                ('owner_type', models.CharField(choices=[('RIDER', 'Rider'), ('USER', 'User')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'rapex_wallets',
                'unique_together': {('owner_id', 'owner_type')},
            },
        ),
        migrations.CreateModel(
            name='RiderRemittanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('DUE_SOON', 'Due Soon'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='CURRENT', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittance_records', to='accounts.riderprofile')),
            ],
            options={
                'db_table': 'rider_remittance_records',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='UserLoyaltyPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('rollover_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_earned', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_loyalty_points',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('TOP_UP', 'Top Up'), ('PAYMENT_TO_MERCHANT', 'Payment to Merchant'), ('DELIVERY_FEE_EARNED', 'Delivery Fee Earned'), ('COMMISSION_DEDUCTED', 'Commission Deducted'), ('INITIAL_LOAD', 'Initial Load'), ('REMITTANCE_DEDUCTED', 'Remittance Deducted'), ('PENALTY', 'Penalty'), ('INCENTIVE', 'Incentive'), ('REFUND', 'Refund'), ('POINTS_REDEEMED', 'Points Redeemed'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive=credit, Negative=debit', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('performed_by_id', models.UUIDField(blank=True, null=True)),
                ('performed_by_role', models.CharField(blank=True, choices=[('SYSTEM', 'System'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'SuperAdmin')], max_length=20, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.rapexwallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
