# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshMarketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fresh_categories', to='merchant.merchantstore')),
            ],
            options={
                'db_table': 'fresh_market_categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FreshMarketProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('RAW_MEAT', 'Raw Meat'), ('SEAFOOD', 'Seafood'), ('POULTRY', 'Poultry'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('pricing_mode', models.CharField(choices=[('PER_PIECE', 'Per Piece'), ('PER_KILO', 'Per Kilo'), ('PER_100G', 'Per 100g'), ('PER_PACK', 'Per Pack'), ('PER_BUNDLE', 'Per Bundle')], default='PER_PIECE', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('markup_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('images', models.JSONField(blank=True, default=list)),
                ('freshness_status', models.CharField(choices=[('FRESH_TODAY', 'Fresh Today'), ('LIMITED', 'Limited'), ('OUT_OF_STOCK', 'Out of Stock')], default='FRESH_TODAY', max_length=20)),
                ('auto_reset_daily', models.BooleanField(default=False)),
                ('merchant_notes', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='fresh_market.freshmarketcategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fresh_products', to='merchant.merchantstore')),
            ],
            options={
                'db_table': 'fresh_market_products',
            },
        ),
    ]
