# Generated by Django 5.1.2 on 2026-03-07 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('FLOAT', 'Float'), ('BOOL', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store_type', models.CharField(choices=[('ALL', 'All'), ('SHOP', 'Shop'), ('FRESH_MARKET', 'Fresh Market'), ('READY_TO_EAT', 'Ready to Eat'), ('PRELOVED', 'Pre-Loved')], default='ALL', max_length=20)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='e.g. 10.00 = 10%', max_digits=5)),
            ],
            options={
                'db_table': 'commission_tiers',
                'ordering': ['store_type', 'price_min'],
                'unique_together': {('store_type', 'price_min')},
            },
        ),
        migrations.CreateModel(
            name='MarkupTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store_type', models.CharField(choices=[('ALL', 'All'), ('SHOP', 'Shop'), ('FRESH_MARKET', 'Fresh Market'), ('READY_TO_EAT', 'Ready to Eat'), ('PRELOVED', 'Pre-Loved')], default='ALL', max_length=20)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('markup_rate', models.DecimalField(decimal_places=2, help_text='e.g. 5.00 = 5%', max_digits=5)),
            ],
            options={
                'db_table': 'markup_tiers',
                'ordering': ['store_type', 'price_min'],
                'unique_together': {('store_type', 'price_min')},
            },
        ),
    ]
