# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('subject_role', models.CharField(choices=[('USER', 'User'), ('MERCHANT', 'Merchant'), ('RIDER', 'Rider')], max_length=15)),
                ('reason', models.TextField()),
                ('is_permanent', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('blacklisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to='accounts.adminprofile')),
            ],
            options={
                'db_table': 'account_blacklist',
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('subject_role', models.CharField(choices=[('USER', 'User'), ('MERCHANT', 'Merchant'), ('RIDER', 'Rider'), ('ORDER', 'Order'), ('TRANSACTION', 'Transaction')], max_length=15)),
                ('flag_type', models.CharField(choices=[('KYC_ANOMALY', 'KYC Anomaly'), ('CANCEL_PATTERN', 'Cancel Pattern'), ('SUSPICIOUS_TRANSACTION', 'Suspicious Transaction'), ('RAPID_REFERRAL', 'Rapid Referral'), ('NON_RESPONSIVE_RIDER', 'Non-Responsive Rider'), ('LATE_REMITTANCE', 'Late Remittance'), ('GPS_MANIPULATION', 'GPS Manipulation'), ('OTHER', 'Other')], max_length=30)),
                ('flag_reason', models.TextField()),
                ('auto_flagged', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('ESCALATED', 'Escalated'), ('BLACKLISTED', 'Blacklisted')], default='PENDING', max_length=15)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to='accounts.adminprofile')),
            ],
            options={
                'db_table': 'fraud_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('subject_id', models.UUIDField()),
                ('subject_role', models.CharField(choices=[('USER', 'User'), ('MERCHANT', 'Merchant'), ('RIDER', 'Rider'), ('ORDER', 'Order'), ('TRANSACTION', 'Transaction')], max_length=15)),
                ('title', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=15)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='accounts.adminprofile')),
                ('fraud_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='fraud.fraudflag')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_cases', to='accounts.adminprofile')),
            ],
            options={
                'db_table': 'investigation_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
