# Generated by Django 5.1.2 on 2026-03-07 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantMarkupOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store_type', models.CharField(blank=True, choices=[('SHOP', 'Shop'), ('FRESH_MARKET', 'Fresh Market'), ('READY_TO_EAT', 'Ready to Eat'), ('PRELOVED', 'Pre-Loved')], help_text='NULL = applies to all stores', max_length=20, null=True)),
                ('tier_1_rate', models.DecimalField(decimal_places=2, help_text='₱1-₱100', max_digits=5)),
                ('tier_2_rate', models.DecimalField(decimal_places=2, help_text='₱101-₱1000', max_digits=5)),
                ('tier_3_rate', models.DecimalField(decimal_places=2, help_text='₱1001+', max_digits=5)),
                ('reason', models.TextField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markup_overrides', to='accounts.merchantprofile')),
                ('set_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.adminprofile')),
            ],
            options={
                'db_table': 'merchant_markup_overrides',
            },
        ),
        migrations.CreateModel(
            name='MerchantStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store_type', models.CharField(choices=[('SHOP', 'Shop'), ('FRESH_MARKET', 'Fresh Market'), ('READY_TO_EAT', 'Ready to Eat'), ('PRELOVED', 'Pre-Loved')], max_length=20)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('banner_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_accepting_delivery', models.BooleanField(default=True)),
                ('is_accepting_pickup', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.merchantprofile')),
            ],
            options={
                'db_table': 'merchant_stores',
                'unique_together': {('merchant', 'store_type')},
            },
        ),
        migrations.CreateModel(
            name='StoreSchedule',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField(help_text='0=Monday, 6=Sunday')),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='merchant.merchantstore')),
            ],
            options={
                'db_table': 'store_schedules',
                'unique_together': {('store', 'day_of_week')},
            },
        ),
    ]
