# Generated by Django 5.2 on 2026-04-15 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_google_id_customuser_profile_image_url_and_more'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantBusinessCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'merchant_business_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MerchantBusinessType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='merchant.merchantbusinesscategory')),
            ],
            options={
                'db_table': 'merchant_business_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MerchantBusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business_name', models.CharField(max_length=200)),
                ('registration_type', models.CharField(choices=[('UNREGISTERED', 'Unregistered'), ('REGISTERED_NON_VAT', 'Registered (NON VAT)'), ('REGISTERED_VAT', 'Registered (VAT Included)')], default='UNREGISTERED', max_length=30)),
                ('categories', models.ManyToManyField(blank=True, related_name='merchant_business_profiles', to='merchant.merchantbusinesscategory')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='accounts.merchantprofile')),
                ('business_types', models.ManyToManyField(blank=True, related_name='merchant_business_profiles', to='merchant.merchantbusinesstype')),
            ],
            options={
                'db_table': 'merchant_business_profiles',
            },
        ),
        migrations.CreateModel(
            name='MerchantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('SELFIE_WITH_ID', 'Selfie with ID'), ('VALID_ID', 'Valid ID'), ('BARANGAY_PERMIT', 'Barangay Permit'), ('DTI_OR_SEC', 'DTI or SEC Certificate'), ('BIR_2303', 'BIR Certificate of Registration (Form 2303)'), ('MAYORS_PERMIT', "Mayor's Permit / Business Permit"), ('OTHER', 'Other Document')], max_length=30)),
                ('file_url', models.CharField(max_length=500)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_documents', to='accounts.merchantprofile')),
            ],
            options={
                'db_table': 'merchant_documents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('house_number', models.CharField(blank=True, default='', max_length=50)),
                ('street_name', models.CharField(blank=True, default='', max_length=200)),
                ('barangay', models.CharField(blank=True, default='', max_length=120)),
                ('city_municipality', models.CharField(blank=True, default='', max_length=120)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
                ('zip_code', models.CharField(blank=True, default='', max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_location', to='accounts.merchantprofile')),
            ],
            options={
                'db_table': 'merchant_locations',
            },
        ),
        migrations.CreateModel(
            name='MerchantOnboardingState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('is_submitted', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('can_resubmit', models.BooleanField(default=False)),
                ('admin_resubmission_note', models.TextField(blank=True, default='')),
                ('draft_payload', models.JSONField(blank=True, default=dict)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to='accounts.merchantprofile')),
            ],
            options={
                'db_table': 'merchant_onboarding_states',
            },
        ),
        migrations.AddConstraint(
            model_name='merchantbusinesstype',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_merchant_business_type_per_category'),
        ),
    ]
