# Generated by Django 5.2 on 2026-04-16 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_merchantbusinesscategory_merchantbusinesstype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCountryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=120, unique=True)),
                ('country_code', models.CharField(max_length=8, unique=True)),
                ('country_flag_emoji', models.CharField(blank=True, default='', max_length=8)),
                ('max_digits', models.PositiveSmallIntegerField(default=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'merchant_country_codes',
                'ordering': ['-is_default', 'country_name'],
            },
        ),
    ]
