# Generated by Django 5.2 on 2026-04-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_merchantcountrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantdocument',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('SELFIE_WITH_ID', 'Selfie with ID'),
                    ('VALID_ID_FRONT', 'Valid ID (Front)'),
                    ('VALID_ID_BACK', 'Valid ID (Back)'),
                    ('BARANGAY_PERMIT', 'Barangay Permit'),
                    ('DTI_OR_SEC', 'DTI or SEC Certificate'),
                    ('BIR_2303', 'BIR Certificate of Registration (Form 2303)'),
                    ('MAYORS_PERMIT', "Mayor's Permit / Business Permit"),
                    ('OTHER', 'Other Document'),
                ],
                max_length=30,
            ),
        ),
    ]
